version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  wildfly:
    build:
      context: .
    container_name: wildfly-server
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: example
      DB_USER: postgres
      DB_PASSWORD: postgres
      DS_NAME: MovieDS
      DS_JNDI: java:/jdbc/MovieDS
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
